name: programmers-be
on :
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: build gradle
        run: ./gradlew -x clean build
        shell: bash
